/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExtensionConnectRouteImport } from './routes/extension.connect'
import { Route as EditorDocumentIdRouteImport } from './routes/editor.$documentId'
import { Route as ApiRenderTypstRouteImport } from './routes/api.render.typst'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionConnectRoute = ExtensionConnectRouteImport.update({
  id: '/extension/connect',
  path: '/extension/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorDocumentIdRoute = EditorDocumentIdRouteImport.update({
  id: '/editor/$documentId',
  path: '/editor/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRenderTypstRoute = ApiRenderTypstRouteImport.update({
  id: '/api/render/typst',
  path: '/api/render/typst',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/generate': typeof GenerateRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/templates': typeof TemplatesRoute
  '/editor/$documentId': typeof EditorDocumentIdRoute
  '/extension/connect': typeof ExtensionConnectRoute
  '/api/render/typst': typeof ApiRenderTypstRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/generate': typeof GenerateRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/templates': typeof TemplatesRoute
  '/editor/$documentId': typeof EditorDocumentIdRoute
  '/extension/connect': typeof ExtensionConnectRoute
  '/api/render/typst': typeof ApiRenderTypstRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/generate': typeof GenerateRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/templates': typeof TemplatesRoute
  '/editor/$documentId': typeof EditorDocumentIdRoute
  '/extension/connect': typeof ExtensionConnectRoute
  '/api/render/typst': typeof ApiRenderTypstRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/generate'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/templates'
    | '/editor/$documentId'
    | '/extension/connect'
    | '/api/render/typst'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/generate'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/templates'
    | '/editor/$documentId'
    | '/extension/connect'
    | '/api/render/typst'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/generate'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/templates'
    | '/editor/$documentId'
    | '/extension/connect'
    | '/api/render/typst'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  GenerateRoute: typeof GenerateRoute
  OnboardingRoute: typeof OnboardingRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TemplatesRoute: typeof TemplatesRoute
  EditorDocumentIdRoute: typeof EditorDocumentIdRoute
  ExtensionConnectRoute: typeof ExtensionConnectRoute
  ApiRenderTypstRoute: typeof ApiRenderTypstRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension/connect': {
      id: '/extension/connect'
      path: '/extension/connect'
      fullPath: '/extension/connect'
      preLoaderRoute: typeof ExtensionConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$documentId': {
      id: '/editor/$documentId'
      path: '/editor/$documentId'
      fullPath: '/editor/$documentId'
      preLoaderRoute: typeof EditorDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/render/typst': {
      id: '/api/render/typst'
      path: '/api/render/typst'
      fullPath: '/api/render/typst'
      preLoaderRoute: typeof ApiRenderTypstRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  GenerateRoute: GenerateRoute,
  OnboardingRoute: OnboardingRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TemplatesRoute: TemplatesRoute,
  EditorDocumentIdRoute: EditorDocumentIdRoute,
  ExtensionConnectRoute: ExtensionConnectRoute,
  ApiRenderTypstRoute: ApiRenderTypstRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
